### ISSUE TITLE
HelloWorldボットのファーストリリース

### ISSUE THREAD

**Issue by i-ishikawa-106** [findix-slackapp/slackapp-hello-world#6]
- [ ] HelloWorldボットを実装しリリースする。
  - 機能：話しかけられたら"Hello World"と答える。
  - 期限：**3月中**

**Comment by t-kikkawa** [comment]
以下を参考に実装しました。
https://github.com/lins05/slackbot
https://qiita.com/sukesuke/items/1ac92251def87357fdf6

ダイレクトメッセージの場合
![スクリーンショット 2019-03-26 15 42 32](https://user-images.githubusercontent.com/41955706/54976588-30b4cc80-4fde-11e9-827e-6e7bf3314d0b.png)

botが参加しているチャンネル(prj-slackapp)の場合
![スクリーンショット 2019-03-26 15 41 59](https://user-images.githubusercontent.com/41955706/54976625-488c5080-4fde-11e9-89f1-3f5bce49944a.png)
![スクリーンショット 2019-03-26 15 44 59](https://user-images.githubusercontent.com/41955706/54976632-4b874100-4fde-11e9-90da-c918c8ac03c7.png)

テストコードの実装はテスト専用のチャンネルが必要なので一旦保留としました。

**Comment by t-kikkawa** [comment]
CodeStarのプロジェクト「slackapp-hello-world」を壊しちゃったので「slackapp-hello-world3」を新たに作りました。
